version: "3.7"
services:
  base-image:
    image: base-image
    build:
      context: .
      dockerfile: Dockerfile
  user:
    # image: users
    volumes:
      - ~/CC:/code
    build:
      context: ~/CC
      dockerfile: ./servs/User1
    
    ports:
      - "8080:80"
    networks:
      microservice_nets:
        ipv4_address: 172.16.238.10
  ride:
    # image: rides
    volumes:
      - ~/CC:/code
    build:
      context: ~/CC
      dockerfile: ./servs/Rides1
    
    ports:
      - "8000:80"
    networks:
      microservice_nets:
        ipv4_address: 172.16.238.11

networks:
  microservice_nets:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
